### ISSUE TITLE
The refresh button doesn't refresh the theme.

### ISSUE THREAD

**Issue by mikidep** [valr/awf#1]
Switching to another one and then switching back doesn't work either. The only way I've found to refresh is closing the application and running it again.

**Comment by zaquest** [comment]
It seems to work currently on both gtk2 (2.24) and gtk3 (3.22).

**Comment by valr** [comment]
Indeed, it's working again now.
I guess it depends on the gtk version. It might (or not) be a bug in gtk.
Closing for now.
