### ISSUE TITLE
ArchLinux Installation Error

### ISSUE THREAD

**Issue by Souravgoswami** [valr/awf#10]
┌─━[sourav::archlinux]─ [/tmp/awf-git]
└──╼> makepkg -si
==> Making package: awf-git v1.3.1.r3.g8a579e6-1 (Mon 25 Feb 2019 23:40:35 IST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Cloning awf-git git repo...
Cloning into bare repository '/tmp/awf-git/awf-git'...
remote: Enumerating objects: 414, done.
remote: Total 414 (delta 0), reused 0 (delta 0), pack-reused 414
Receiving objects: 100% (414/414), 774.15 KiB | 168.00 KiB/s, done.
Resolving deltas: 100% (193/193), done.
==> Validating source files with md5sums...
    awf-git ... Skipped
==> Extracting sources...
  -> Creating working copy of awf-git git repo...
Cloning into 'awf-git'...
done.
==> Starting pkgver()...
==> Updated version: awf-git v1.4.0.r0.gc937f1b-1
==> Starting build()...
configure.ac:6: installing './compile'
configure.ac:4: installing './install-sh'
configure.ac:4: installing './missing'
src/Makefile.am: installing './depcomp'
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of gcc... gcc3
./configure: line 3411: syntax error near unexpected token `GTK3,'
./configure: line 3411: `PKG_CHECK_MODULES(GTK3, gtk+-3.0, GTK3_SUFFIX=gtk3,'
==> ERROR: A failure occurred in build().
    Aborting...

**Comment by Souravgoswami** [comment]
I am using xfce4. I have the gtk2 and gtk3 packages installed. I have installed awf on another computer running the same OS on same architecture about a month ago, which works fine. This is the error I am getting for the first time!

**Comment by Souravgoswami** [comment]
This is to be noted that I have the gtk3 and gtk2 installed.
I have also installed awf on a different machine with the same OS and same architecture a month ago! That worked fine.

**Comment by valr** [comment]
@Souravgoswami, can you confirm you have installed all packages from the base (I guess yes) and base-devel groups? base-devel is a pre-requisite for building aur packages.

**Comment by Souravgoswami** [comment]
Oh sorry, I had some of the base-devel packages installed, but I just installed the group, and yes it installed fine!
