### ISSUE TITLE
debian package installation collide with xfce4-session

### ISSUE THREAD

**Issue by prdatur** [valr/awf#3]
I have tried to install it with checkinstall
./autogen.sh
./configure
make -j 8
sudo checkinstall
I changed the maintainer, summary and require fields
maintainer = github url
summary = AWF A-Widget-Factory
require field = empty because the string "gtk2 gtk3" results in an error

Then I get the following error:
(Lese Datenbank ... 324883 Dateien und Verzeichnisse sind derzeit installiert.)
Entpacken von a-widget-factory (aus a-widget-factory_1.3.0-raring_amd64.deb) ...
dpkg: Fehler beim Bearbeiten von a-widget-factory_1.3.0-raring_amd64.deb (--install):
 Versuch, »/usr/local/share/icons/hicolor/icon-theme.cache« zu überschreiben, welches auch in Paket xfce4-session 4.10.0-1 ist
dpkg-deb: Fehler: Unterprozess einfügen wurde durch Signal (Datenübergabe unterbrochen (broken pipe)) getötet
Fehler traten auf beim Bearbeiten von:
 a-widget-factory_1.3.0-raring_amd64.deb

The german text tells me that the install want to override /usr/local/share/icons/hicolor/icon-theme.cache but xfce4-session provides the same file.

**Comment by valr** [comment]
No feedback, closing
