### ISSUE TITLE
Vertical progress bar usually grow top to bottom

### ISSUE THREAD

**Issue by Celelibi** [valr/awf#5]
As the documentation say, with GTK 3 a vertical progress bar usually grow from top to bottom.
https://developer.gnome.org/gtk3/stable/GtkProgressBar.html#gtk-progress-bar-set-inverted

So this set an inconsistency between the GTK 2 and GTK 3 versions. Too bad when comparing the theme rendering between the two versions.

**Comment by valr** [comment]
@Celelibi : thanks for the bug report.
I've just released version 1.3.1 fixing this issue.
Cheers,
V.
